// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accommodation.sql

package queries

import (
	"context"
)

const getAccommodations = `-- name: GetAccommodations :many
SELECT id, tripid, title, address, start_date, end_date FROM accommodations
WHERE tripId = ?
`

func (q *Queries) GetAccommodations(ctx context.Context, tripid int32) ([]Accommodation, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodations, tripid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Accommodation
	for rows.Next() {
		var i Accommodation
		if err := rows.Scan(
			&i.ID,
			&i.Tripid,
			&i.Title,
			&i.Address,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
