// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: itinerary_item.sql

package queries

import (
	"context"
	"database/sql"
)

const getItineraryItems = `-- name: GetItineraryItems :many
SELECT itemid, tripid, title, location, date FROM Itinerary_Items
WHERE TripID = ?
`

func (q *Queries) GetItineraryItems(ctx context.Context, tripid sql.NullInt32) ([]ItineraryItem, error) {
	rows, err := q.db.QueryContext(ctx, getItineraryItems, tripid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItineraryItem
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.Itemid,
			&i.Tripid,
			&i.Title,
			&i.Location,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
