// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: trip.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const getTripsByUser = `-- name: GetTripsByUser :many
SELECT tripId, title, location, userId, CAST(start_date AS DATE) AS start_date, CAST(end_date AS DATE) AS end_date
FROM Trips
WHERE userId = ?
`

type GetTripsByUserRow struct {
	Tripid    int32
	Title     sql.NullString
	Location  sql.NullString
	Userid    sql.NullInt32
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetTripsByUser(ctx context.Context, userid sql.NullInt32) ([]GetTripsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getTripsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTripsByUserRow
	for rows.Next() {
		var i GetTripsByUserRow
		if err := rows.Scan(
			&i.Tripid,
			&i.Title,
			&i.Location,
			&i.Userid,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
