// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: trip.sql

package queries

import (
	"context"
	"database/sql"
)

const getTripsByUser = `-- name: GetTripsByUser :many
SELECT tripid, title, location, userid, start_date, end_date FROM Trips
WHERE userId = ?
`

func (q *Queries) GetTripsByUser(ctx context.Context, userid sql.NullInt32) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, getTripsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.Tripid,
			&i.Title,
			&i.Location,
			&i.Userid,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
